version: '3.3'

services:
  mongo:
    image: mongo
    ports:
      - 8089:27017
    volumes:
      - mongodb:/data/db
    networks:
      - kong-net
  app:
    container_name: 'product_services'
    build: .
    volumes:
      - .:/product_services
      - node_modules:/app/node_modules
    ports: 
      - 3002:3002
    stdin_open: true
    environment:
      - PORT=3001
    command: npm run dev
    networks:
      - kong-net
networks:
  kong-net:
    external: true
volumes:
  mongodb:
  node_modules:
